name: Command iConomy
main: com.ryanmichela.cmdiconomy.CIPlugin
version: 8
website: https://github.com/rmichela/Command-iConomy
author: Ryan Michela, Max Kalus

permissions:
  commandiconomy.free:
    description: All commands are free of charge
    default: false
